spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: localhost:8191
          predicates:
            - Path=/user/
        - id: video-service
          uri: localhost:8190
          predicates:
            - Path=/video/
server:
  port: 5555
  servlet:
    context-path: /api
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/