spring:
  application:
    name: video-service
  cloud:
    kubernetes:
      enabled: false

server:
  port: 8190
  servlet:
    context-path: /video

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8880/auth/user
    client:
      client-id: flametoken
      client-secret: thisissecret